### ISSUE TITLE
ESP32 Issue

### ISSUE THREAD

**Issue by FreldoSK** [liske/python-apds9960#15]
I installed this library via Thonny packages and after running the example it throws me this error:
Warning: I2C(-1, ...) is deprecated, use SoftI2C(...) instead
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/lib/apds9960/device.py", line 41, in __init__
  File "/lib/apds9960/exceptions.py", line 3, in __init__
AttributeError: type object 'Exception' has no attribute '__init__'

Can you please help me?

**Comment by panthertrader** [comment]
I have the same problem.

**Comment by liske** [comment]
Should be fixed by #18.
