### ISSUE TITLE
Gestures are not working on ESP32

### ISSUE THREAD

**Issue by plugowski** [liske/python-apds9960#7]
When I try to run example gesture code I get:

```
Gesture Test
============
Traceback (most recent call last):
  File "<stdin>", line 31, in <module>
  File "apds9960/device.py", line 185, in readGesture
  File "apds9960/device.py", line 1103, in _read_i2c_block_data
OSError: I2C bus error (6)
```

Any ideas what is wrong?

**Comment by coffice12** [comment]
exec(open('test_ambient.py').read(),globals())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 10, in <module>
  File "apds9960/device.py", line 41, in __init__
  File "apds9960/exceptions.py", line 3, in __init__
AttributeError: type object 'Exception' has no attribute '__init__'

me too，my function error

**Comment by liske** [comment]
> exec(open('test_ambient.py').read(),globals())
> Traceback (most recent call last):
> File "", line 1, in
> File "", line 10, in
> File "apds9960/device.py", line 41, in **init**
> File "apds9960/exceptions.py", line 3, in **init**
> AttributeError: type object 'Exception' has no attribute '**init**'
> 
> me too，my function error

@coffice12 this is not related since it is triggered by an unknown device ID (#10)
